# ###### MongoDB
# imports:
#   - { resource: ./application.yaml }

# services:
#   Mooc.EnvironmentArranger:
#     class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
#     arguments: ['@Mooc.ConnectionManager']


imports:
  - { resource: ./application.yaml }

services:
  Mooc.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/typeorm/TypeOrmEnvironmentArranger
    arguments: ['@Mooc.ConnectionManager']
