name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Cucumber can only run on Node.js versions 14 || 16 || >=18. This Node.js version is v15.14.0
        # node-version: [14.x, 15.x, 18.x]
        node-version: [14.x, 18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: npm run lint
        run: |
          npm run lint
      - name: npm run build
        run: |
          npm run build --if-present
      - name: npm test
        run: |
          npm test
